### PR TITLE
community refactoring

### PR DESCRIPTION
**Pull request by MidnightWonderer**
IMO you should refrain from performing offensive monkey patching to other libraries.  
This is my proposal to move forward with the community.

### CODE REVIEW

**Comment by MidnightWonderer** [comment]
I see the other guy already propose this change.  
I'll leave the PR open for the sake of showing my opinions.

**Comment by domagojk** [comment]
Thank you! I will definitely merge most of this PR! 
Yes, custom operator is already prepared to be available as an option. Since it's a breaking change I will publish it in version 3, as soon as docs (readme) is ready.

Why are you proposing `.keep` file for `dist` directory? Are there any errors if it's not present?

I never used peer decencies, and you are right, that is exactly what recycle should specify. But, is this a breaking change or can it be published as a patch?

By the way, creating custom operators is not "monkey patching" but object extension :)

**Comment by MidnightWonderer** [comment]
`prepublish` was broken without dist directory.  
Just try removing dist and `npm install` to see what was broken.  
  
I commit is such way that it is easy to `cherry-pick`. Feel free to pick individual changes to your branch and you can reject this pull request afterward.

**Comment by domagojk** [comment]
I "cherry-picked" two of your commits :)

I don't want extra directories in git so I created `clean` script which removes and creates `dist` and `lib` directories. It works only in unix systems which is not perfect but that should be fixed with https://github.com/recyclejs/recycle/issues/18

As I mentioned, I will make custom RxJS `reducer` operator will be optional for version 3.

Thank you @MidnightWonderer 👊

**Pull request closed without merging**
